### ISSUE TITLE
vcm resampled

### ISSUE THREAD

**Issue by tigrazone** [yuphin/Lumen#20]
please shortly explain how you use restir in vcm integrator

**Comment by yuphin** [comment]
Sorry for the late reply. Basically while tracing from the area light source, for each spatial hash on the light source, we define reservoirs that define the outgoing direction for that spatial patch. This "guides" the light distribution towards the camera. Since this only works for the 0th bounce from the light source (i.e on the light), although it guides the light in a meaningful manner, it did not exhibit a meaningful variance reduction in complex enough cases. One of the future work is to extend this to multiple bounces, but this require either having a very large spatial cell, a KD-tree based data structure or some other experimental work that I've yet to try. Let me know if you have additional questions.

**Comment by tigrazone** [comment]
thank you for explaination
